### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "png_set_longjmp_fn" referenced by "liblept.so"...

### ISSUE THREAD

**Issue by Linkaan** [rmtheis/tess-two#106]
When trying to load the `lept` library, my app crashes because apparently it can't locate symbol "png_set_longjmp_fn". I tried rebuilding the libpng shared library by the name libpng-1.6.2 and changing to `System.loadLibrary("png-1.6.2");`in `TestBaseAPI.java` but it still crashes my app. I am using <a href="https://github.com/GautamGupta/Simple-Android-OCR">this example</a> and I've compiled tess-two with the latest ndk 32 bit version.

Here is the full stacktrace:
```
08-10 15:49:07.450  30307-30307/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.example.myapp PID: 30307
    java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "png_set_longjmp_fn" referenced by "liblept.so"...
            at java.lang.Runtime.loadLibrary(Runtime.java:364)
            at java.lang.System.loadLibrary(System.java:526)
            at com.googlecode.tesseract.android.TessBaseAPI.<clinit>(TessBaseAPI.java:44)
            at com.example.myapp.SimpleAndroidOCRActivity.onPhotoTaken(SimpleAndroidOCRActivity.java:211)
            at com.example.myapp.SimpleAndroidOCRActivity.onActivityResult(SimpleAndroidOCRActivity.java:135)
            at android.app.Activity.dispatchActivityResult(Activity.java:5423)
            at android.app.ActivityThread.deliverResults(ActivityThread.java:3385)
            at android.app.ActivityThread.handleSendResult(ActivityThread.java:3432)
            at android.app.ActivityThread.access$1300(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1253)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5146)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
            at dalvik.system.NativeStart.main(Native Method)
```

Here is my build.gradle file:
```gradle
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:0.9.+'
    }
}

apply plugin: 'android-library'

android {
    compileSdkVersion 22
    buildToolsVersion "22.0.1"

    defaultConfig {
        minSdkVersion 8
        targetSdkVersion 19
    }

    sourceSets.main {
        manifest.srcFile 'AndroidManifest.xml'
        java.srcDirs = ['src']
        resources.srcDirs = ['src']
        res.srcDirs = ['res']
        jniLibs.srcDirs = ['libs']
    }
}
```

I'm running this on my Samsung Galaxy S4 ks01lte running Cyanogen-mod.

**Comment by rmtheis** [comment]
Do you get the same error when you run the unit tests?

**Comment by rmtheis** [comment]
And do you also get the same error when you run on a non-Cyanogen-mod device, or an emulator?

**Comment by Linkaan** [comment]
@rmtheis I will try. How would I run the unit tests? I am using windows as my development machine.

**Comment by smac89** [comment]
@Linkaan if you are using android studio, you should post your build.gradle file for tess-two

**Comment by Linkaan** [comment]
@smac89 Thanks for the tip, I just added it.

**Comment by festplatte** [comment]
I got the same error while trying to get a new instance of TessBaseAPI and I think that it's a bug in the master version of tess-two. Now I downloaded version 5.1.0 and everything works just fine. Maybe this can solve your problem, too.

**Comment by smac89** [comment]
@Linkaan 
If you still didn't get it to work for you, try this build.gradle file:

```
apply plugin: 'com.android.library'

android {

    compileSdkVersion 23
    buildToolsVersion "23.0.0"


    defaultConfig {
        minSdkVersion 8
        targetSdkVersion 22

        ndk {
            moduleName "tess-two"
        }
    }


    sourceSets.main {
        manifest.srcFile 'AndroidManifest.xml'
        java.srcDirs = ['src']
        resources.srcDirs = ['src']
        res.srcDirs = ['res']
        jniLibs.srcDir 'libs'
        jni.srcDirs = []
        aidl.srcDirs = ['src']
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-project.txt')
        }
    }
}
```

**Comment by mhd-adeeb-masoud** [comment]
In my case it's only happening on my note II. All my other devices are working fine.
@Linkaan I tried your solution also did not work.
I will try to pull 5.1 and try again :)

**Comment by makelove** [comment]
downloaded version 5.2.0 ,every problems is gone.

**Comment by rmtheis** [comment]
http://stackoverflow.com/questions/20698905/unsatisfiedlinkerror-in-android-4-4-libdevil-cannot-locate-symbol-png-set-longj

**Comment by rmtheis** [comment]
@Linkaan Thanks for the report. This is fixed in the latest commit.

**Comment by julianoabrs** [comment]
I'm sorry, but version 5.2.0 of what component?!
