### ISSUE TITLE
UnsatisfiedLinkError: Couldn't load jpgt from loader

### ISSUE THREAD

**Issue by aneeshATgithub** [rmtheis/tess-two#169]
I have builded tess-two using "android-ndk-r12b" in ubuntu, and I have imported it to my project as #module dependency, 

** My project structure is as follows,** 

![project_structure](https://cloud.githubusercontent.com/assets/12003616/17732998/1e5662e0-6492-11e6-976c-7bec1966be3e.png)
**When I initializing TessBaseAPI, the app crashes and I am getting the following log,**

 Caused by: java.lang.UnsatisfiedLinkError: Couldn't load jpgt from loader dalvik.system.PathClassLoader[dexPath=/data/app/phenomtec.com.tessnative-1.apk,libraryPath=/data/app-lib/phenomtec.com.tessnative-1]: findLibrary returned null
                                                                              at java.lang.Runtime.loadLibrary(Runtime.java:365)
                                                                              at java.lang.System.loadLibrary(System.java:535)
                                                                              at com.googlecode.tesseract.android.TessBaseAPI.<clinit>(TessBaseAPI.java:50)
                                                                              at phenomtec.com.tessnative.MainActivity.detectText(MainActivity.java:37) 
                                                                              at phenomtec.com.tessnative.MainActivity.onCreate(MainActivity.java:32) 
                                                                              at android.app.Activity.performCreate(Activity.java:5283) 
                                                                              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1097) 
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2209) 
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2295) 
                                                                              at android.app.ActivityThread.access$700(ActivityThread.java:150) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1280) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                              at android.os.Looper.loop(Looper.java:175) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5279) 
                                                                              at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                              at java.lang.reflect.Method.invoke(Method.java:511)

**Comment by rmtheis** [comment]
There's not enough information here to reproduce this problem, and it appears to be a problem with your app's setup and not a problem with this project. I'd suggest using the precompiled version instead (see "Usage" in the Readme).

**Comment by aneeshATgithub** [comment]
Can you please explain what the app's setup need to change by me? And I had used the precompiled version but the there the default  orientation was landscape. And I had also tried portrait according to the suggestion that you had commented early for someone's isssu post. But when capturing in portrait mode, the image processing is very poor.
